---
apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  labels:
    app: "greeter-server"
spec:
  ports:
    - port: 7788
      name: "grpc-greeter"
      protocol: TCP
  selector:
    app: "greeter-server"
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-http-server
  labels:
    app: "greeter-server"
spec:
  ports:
    - port: 7789
      name: "http-greeter"
      protocol: TCP
  selector:
    app: "greeter-server"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter-server
  labels:
    app: greeter-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: "greeter-server"
  template:
    metadata:
      labels:
        app: "greeter-server"
      annotations:
          sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: greeter-server
        image: "prune/gohellogrpcstream:istio"      
        ports:
        - containerPort: 7788
          name: grpc-greeter
        - containerPort: 7789
          name: http-greeter
        command: 
          - "/root/greeter_server"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadtest-client
  labels:
    app: loadtest-client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: "loadtest-client"
  template:
    metadata:
      labels:
        app: "loadtest-client"
      annotations:
          sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: loadtest-client
        image: "prune/gohellogrpcstream:istio"      
        ports:
        - containerPort: 7789
          name: loadtest-client
        command: 
          - "tail"
          - "-f"
          - "/dev/null"
        env:
          - name: "CLIENTS"
            value: "400"
          - name: "SERVER"
            value: "greeter-server:7788"
          - name: "CNXDELAY"
            value: "2000s"
